package com.apartment.management.model;

import java.util.Date;

public class BookRoom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_room.id
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_room.user_name
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_room.id_card
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_room.room_nummber
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    private Integer roomNummber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_room.in_time
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    private Date inTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_room.out_time
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    private Date outTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_room.deposit
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    private Integer deposit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_room.id
     *
     * @return the value of book_room.id
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_room.id
     *
     * @param id the value for book_room.id
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_room.user_name
     *
     * @return the value of book_room.user_name
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_room.user_name
     *
     * @param userName the value for book_room.user_name
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_room.id_card
     *
     * @return the value of book_room.id_card
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_room.id_card
     *
     * @param idCard the value for book_room.id_card
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_room.room_nummber
     *
     * @return the value of book_room.room_nummber
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public Integer getRoomNummber() {
        return roomNummber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_room.room_nummber
     *
     * @param roomNummber the value for book_room.room_nummber
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public void setRoomNummber(Integer roomNummber) {
        this.roomNummber = roomNummber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_room.in_time
     *
     * @return the value of book_room.in_time
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_room.in_time
     *
     * @param inTime the value for book_room.in_time
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_room.out_time
     *
     * @return the value of book_room.out_time
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_room.out_time
     *
     * @param outTime the value for book_room.out_time
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_room.deposit
     *
     * @return the value of book_room.deposit
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public Integer getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_room.deposit
     *
     * @param deposit the value for book_room.deposit
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    public void setDeposit(Integer deposit) {
        this.deposit = deposit;
    }
}