package com.apartment.management.model;

public class GoodManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_manage.goods_id
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_manage.goods_nums
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    private Integer goodsNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_manage.goods_name
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_manage.goods_price
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    private Float goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_manage.goods_number
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    private Integer goodsNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_manage.goods_id
     *
     * @return the value of good_manage.goods_id
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_manage.goods_id
     *
     * @param goodsId the value for good_manage.goods_id
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_manage.goods_nums
     *
     * @return the value of good_manage.goods_nums
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    public Integer getGoodsNums() {
        return goodsNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_manage.goods_nums
     *
     * @param goodsNums the value for good_manage.goods_nums
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    public void setGoodsNums(Integer goodsNums) {
        this.goodsNums = goodsNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_manage.goods_name
     *
     * @return the value of good_manage.goods_name
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_manage.goods_name
     *
     * @param goodsName the value for good_manage.goods_name
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_manage.goods_price
     *
     * @return the value of good_manage.goods_price
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    public Float getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_manage.goods_price
     *
     * @param goodsPrice the value for good_manage.goods_price
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    public void setGoodsPrice(Float goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_manage.goods_number
     *
     * @return the value of good_manage.goods_number
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_manage.goods_number
     *
     * @param goodsNumber the value for good_manage.goods_number
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }
}