package com.apartment.management.model;

import java.util.Date;

public class RoomManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_manage.id
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_manage.room_nums
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    private Integer roomNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_manage.username
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_manage.check_in
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    private Integer checkIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_manage.status
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_manage.in_time
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    private Date inTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_manage.out_time
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    private Date outTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_manage.id
     *
     * @return the value of room_manage.id
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_manage.id
     *
     * @param id the value for room_manage.id
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_manage.room_nums
     *
     * @return the value of room_manage.room_nums
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public Integer getRoomNums() {
        return roomNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_manage.room_nums
     *
     * @param roomNums the value for room_manage.room_nums
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public void setRoomNums(Integer roomNums) {
        this.roomNums = roomNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_manage.username
     *
     * @return the value of room_manage.username
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_manage.username
     *
     * @param username the value for room_manage.username
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_manage.check_in
     *
     * @return the value of room_manage.check_in
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public Integer getCheckIn() {
        return checkIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_manage.check_in
     *
     * @param checkIn the value for room_manage.check_in
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public void setCheckIn(Integer checkIn) {
        this.checkIn = checkIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_manage.status
     *
     * @return the value of room_manage.status
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_manage.status
     *
     * @param status the value for room_manage.status
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_manage.in_time
     *
     * @return the value of room_manage.in_time
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_manage.in_time
     *
     * @param inTime the value for room_manage.in_time
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_manage.out_time
     *
     * @return the value of room_manage.out_time
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_manage.out_time
     *
     * @param outTime the value for room_manage.out_time
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }
}