package com.apartment.management.mapper;

import com.apartment.management.model.BookRoom;
import com.apartment.management.model.BookRoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BookRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    int countByExample(BookRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    int deleteByExample(BookRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    int insert(BookRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    int insertSelective(BookRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    List<BookRoom> selectByExampleWithRowbounds(BookRoomExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    List<BookRoom> selectByExample(BookRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    BookRoom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") BookRoom record, @Param("example") BookRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    int updateByExample(@Param("record") BookRoom record, @Param("example") BookRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    int updateByPrimaryKeySelective(BookRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_room
     *
     * @mbggenerated Sun May 17 22:12:23 CST 2020
     */
    int updateByPrimaryKey(BookRoom record);
}