package com.apartment.management.mapper;

import com.apartment.management.model.GoodManage;
import com.apartment.management.model.GoodManageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GoodManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    int countByExample(GoodManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    int deleteByExample(GoodManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    int insert(GoodManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    int insertSelective(GoodManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    List<GoodManage> selectByExampleWithRowbounds(GoodManageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    List<GoodManage> selectByExample(GoodManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    GoodManage selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") GoodManage record, @Param("example") GoodManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    int updateByExample(@Param("record") GoodManage record, @Param("example") GoodManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    int updateByPrimaryKeySelective(GoodManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_manage
     *
     * @mbggenerated Tue May 19 23:38:23 CST 2020
     */
    int updateByPrimaryKey(GoodManage record);
}