package com.apartment.management.mapper;

import com.apartment.management.model.RoomManage;
import com.apartment.management.model.RoomManageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RoomManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    int countByExample(RoomManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    int deleteByExample(RoomManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    int insert(RoomManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    int insertSelective(RoomManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    List<RoomManage> selectByExampleWithRowbounds(RoomManageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    List<RoomManage> selectByExample(RoomManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    RoomManage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoomManage record, @Param("example") RoomManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    int updateByExample(@Param("record") RoomManage record, @Param("example") RoomManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    int updateByPrimaryKeySelective(RoomManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_manage
     *
     * @mbggenerated Mon May 18 21:31:40 CST 2020
     */
    int updateByPrimaryKey(RoomManage record);

}